export const FETCH_STOCK_EPSSES = "FETCH_STOCK_EPSSES";
export const FETCH_STOCK_EPSSES_START = "FETCH_STOCK_EPSSES_START";
export const FETCH_STOCK_EPSSES_SUCCESS = "FETCH_STOCK_EPSSES_SUCCESS";
export const FETCH_STOCK_EPSSES_FAIL = "FETCH_STOCK_EPSSES_FAIL";

export const FETCH_STOCK_EPSS = "FETCH_STOCK_EPSS";
export const FETCH_STOCK_EPSS_START = "FETCH_STOCK_EPSS_START";
export const FETCH_STOCK_EPSS_SUCCESS = "FETCH_STOCK_EPSS_SUCCESS";
export const FETCH_STOCK_EPSS_FAIL = "FETCH_STOCK_EPSS_FAIL";

export const UPDATE_STOCK_EPSS = "UPDATE_STOCK_EPSS";
export const RESET_STOCK_EPSS = "RESET_STOCK_EPSS";

export const SAVE_STOCK_EPSS = "SAVE_STOCK_EPSS";
export const SAVE_STOCK_EPSS_START = "SAVE_STOCK_EPSS_START";
export const SAVE_STOCK_EPSS_SUCCESS = "SAVE_STOCK_EPSS_SUCCESS";
export const SAVE_STOCK_EPSS_FAIL = "SAVE_STOCK_EPSS_FAIL";

export const DELETE_STOCK_EPSS = "DELETE_STOCK_EPSS";
export const DELETE_STOCK_EPSS_START = "DELETE_STOCK_EPSS_START";
export const DELETE_STOCK_EPSS_SUCCESS = "DELETE_STOCK_EPSS_SUCCESS";
export const DELETE_STOCK_EPSS_FAIL = "DELETE_STOCK_EPSS_FAIL";

//--export
