export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_CHATS_START = "FETCH_CHATS_START";
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAIL = "FETCH_CHATS_FAIL";

export const FETCH_CHAT = "FETCH_CHAT";
export const FETCH_CHAT_START = "FETCH_CHAT_START";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAIL = "FETCH_CHAT_FAIL";

export const UPDATE_CHAT = "UPDATE_CHAT";
export const RESET_CHAT = "RESET_CHAT";

export const SAVE_CHAT = "SAVE_CHAT";
export const SAVE_CHAT_START = "SAVE_CHAT_START";
export const SAVE_CHAT_SUCCESS = "SAVE_CHAT_SUCCESS";
export const SAVE_CHAT_FAIL = "SAVE_CHAT_FAIL";

export const DELETE_CHAT = "DELETE_CHAT";
export const DELETE_CHAT_START = "DELETE_CHAT_START";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAIL = "DELETE_CHAT_FAIL";

export const CONNECT_CHAT = "CONNECT_CHAT";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const CONNECT_CHAT_START = "CONNECT_CHAT_START";
export const CONNECT_CHAT_SUCCESS = "CONNECT_CHAT_SUCCESS";
export const CONNECT_CHAT_ERROR = "CONNECT_CHAT_ERROR";
