export const FETCH_TMPITEMS = "FETCH_TMPITEMS";
export const FETCH_TMPITEMS_START = "FETCH_TMPITEMS_START";
export const FETCH_TMPITEMS_SUCCESS = "FETCH_TMPITEMS_SUCCESS";
export const FETCH_TMPITEMS_FAIL = "FETCH_TMPITEMS_FAIL";

export const FETCH_TMPITEM = "FETCH_TMPITEM";
export const FETCH_TMPITEM_START = "FETCH_TMPITEM_START";
export const FETCH_TMPITEM_SUCCESS = "FETCH_TMPITEM_SUCCESS";
export const FETCH_TMPITEM_FAIL = "FETCH_TMPITEM_FAIL";

export const UPDATE_TMPITEM = "UPDATE_TMPITEM";
export const RESET_TMPITEM = "RESET_TMPITEM";

export const SAVE_TMPITEM = "SAVE_TMPITEM";
export const SAVE_TMPITEM_START = "SAVE_TMPITEM_START";
export const SAVE_TMPITEM_SUCCESS = "SAVE_TMPITEM_SUCCESS";
export const SAVE_TMPITEM_FAIL = "SAVE_TMPITEM_FAIL";

export const DELETE_TMPITEM = "DELETE_TMPITEM";
export const DELETE_TMPITEM_START = "DELETE_TMPITEM_START";
export const DELETE_TMPITEM_SUCCESS = "DELETE_TMPITEM_SUCCESS";
export const DELETE_TMPITEM_FAIL = "DELETE_TMPITEM_FAIL";
