export const FETCH_STOCK_GROUP_ITEMS = "FETCH_STOCK_GROUP_ITEMS";
export const FETCH_STOCK_GROUP_ITEMS_START = "FETCH_STOCK_GROUP_ITEMS_START";
export const FETCH_STOCK_GROUP_ITEMS_SUCCESS = "FETCH_STOCK_GROUP_ITEMS_SUCCESS";
export const FETCH_STOCK_GROUP_ITEMS_FAIL = "FETCH_STOCK_GROUP_ITEMS_FAIL";

export const FETCH_STOCK_GROUP_ITEM = "FETCH_STOCK_GROUP_ITEM";
export const FETCH_STOCK_GROUP_ITEM_START = "FETCH_STOCK_GROUP_ITEM_START";
export const FETCH_STOCK_GROUP_ITEM_SUCCESS = "FETCH_STOCK_GROUP_ITEM_SUCCESS";
export const FETCH_STOCK_GROUP_ITEM_FAIL = "FETCH_STOCK_GROUP_ITEM_FAIL";

export const UPDATE_STOCK_GROUP_ITEM = "UPDATE_STOCK_GROUP_ITEM";
export const RESET_STOCK_GROUP_ITEM = "RESET_STOCK_GROUP_ITEM";

export const SAVE_STOCK_GROUP_ITEM = "SAVE_STOCK_GROUP_ITEM";
export const SAVE_STOCK_GROUP_ITEMS = "SAVE_STOCK_GROUP_ITEMS";
export const SAVE_STOCK_GROUP_ITEM_START = "SAVE_STOCK_GROUP_ITEM_START";
export const SAVE_STOCK_GROUP_ITEM_SUCCESS = "SAVE_STOCK_GROUP_ITEM_SUCCESS";
export const SAVE_STOCK_GROUP_ITEM_FAIL = "SAVE_STOCK_GROUP_ITEM_FAIL";
export const ADD_STOCK_GROUP_STOCKS = "ADD_STOCK_GROUP_STOCKS";

export const DELETE_STOCK_GROUP_ITEM = "DELETE_STOCK_GROUP_ITEM";
export const DELETE_STOCK_GROUP_ITEM_START = "DELETE_STOCK_GROUP_ITEM_START";
export const DELETE_STOCK_GROUP_ITEM_SUCCESS = "DELETE_STOCK_GROUP_ITEM_SUCCESS";
export const DELETE_STOCK_GROUP_ITEM_FAIL = "DELETE_STOCK_GROUP_ITEM_FAIL";

export const FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS = "FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS";
export const FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS_START = "FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS_START";
export const FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS_SUCCESS =
  "FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS_SUCCESS";
export const FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS_FAIL = "FETCH_STOCK_GROUP_ITEM_AUDIT_LOGS_FAIL";

