export default {
    FETCH_STOCKS_START: "FETCH_STOCKS_START",
    FETCH_STOCKS_SUCCESS: "FETCH_STOCKS_SUCCESS",
    FETCH_STOCKS_FAIL: "FETCH_STOCKS_FAIL",
    ADD_STOCK_SUCCESS: "ADD_STOCK_SUCCESS",
    UPDATE_STOCK_SUCCESS: "UPDATE_STOCK_SUCCESS",
    DEL_STOCK_SUCCESS: "DEL_STOCK_SUCCESS",
};