export default {
    FETCH_CALENDAR_EVENTS: "FETCH_CALENDAR_EVENTS",
    ADD_CALENDAR_EVENTS: "ADD_CALENDAR_EVENTS",
    DEL_CALENDAR_EVENT: "DEL_CALENDAR_EVENT",
    UPDATE_CALENDAR_EVENT: "UPDATE_CALENDAR_EVENT",
};