export default {
    FETCH_CALENDAR_EVENTS_START: "FETCH_CALENDAR_EVENTS_START",
    FETCH_CALENDAR_EVENTS_SUCCESS: "FETCH_CALENDAR_EVENTS_SUCCESS",
    FETCH_CALENDAR_EVENTS_FAIL: "FETCH_CALENDAR_EVENTS_FAIL",
    ADD_CALENDAR_EVENTS_SUCCESS: "ADD_CALENDAR_EVENTS_SUCCESS",
    UPDATE_CALENDAR_EVENT_SUCCESS: "UPDATE_CALENDAR_EVENT_SUCCESS",
    DEL_CALENDAR_EVENTS_SUCCESS: "DEL_CALENDAR_EVENTS_SUCCESS",
};