export default {
    FETCH_AWESOME_PAGES_START: "FETCH_AWESOME_PAGES_START",
    FETCH_AWESOME_PAGES_SUCCESS: "FETCH_AWESOME_PAGES_SUCCESS",
    FETCH_AWESOME_PAGES_FAIL: "FETCH_AWESOME_PAGES_FAIL",
    ADD_AWESOME_PAGE_SUCCESS: "ADD_AWESOME_PAGE_SUCCESS",
    UPDATE_AWESOME_PAGE_SUCCESS: "UPDATE_AWESOME_PAGE_SUCCESS",
    DEL_AWESOME_PAGE_SUCCESS: "DEL_AWESOME_PAGE_SUCCESS",
};