trigger:
 branches:
  include:
    - minsDream
 paths:
  include:
    - src/Monolith/ClassifiedAds.VueWeb/**

pool: Default

variables:
  project: $(Build.SourcesDirectory)/src/Monolith/ClassifiedAds.VueWeb/ClassifiedAds.VueWeb.csproj
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(project)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(12f9fe73-501c-467e-b224-dc534d3b5bb3)'
    appType: 'webApp'
    appName: 'minsDream-tst-vue'
    deployToSlotOrASE: true
    resourceGroupName: 'Test'
    slotName: 'production'
    package: '$(Build.ArtifactStagingDirectory)/ClassifiedAds.VueWeb.zip'
    deploymentMethod: 'zipDeploy'
