# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - minsDream
 paths:
  include:
    - src/Monolith/ClassifiedAds.IdentityServer/**

pool: Default

variables:
  project: $(Build.SourcesDirectory)/src/Monolith/ClassifiedAds.IdentityServer/ClassifiedAds.IdentityServer.csproj
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(project)

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(project)
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: $(project)
    zipAfterPublish: True

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(12f9fe73-501c-467e-b224-dc534d3b5bb3)'
    appType: 'webApp'
    appName: 'minsDream-tst-identity'
    deployToSlotOrASE: true
    resourceGroupName: 'Test'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'zipDeploy'