export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS_START = "FETCH_NOTIFICATIONS_START";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAIL = "FETCH_NOTIFICATIONS_FAIL";

export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
export const FETCH_NOTIFICATION_START = "FETCH_NOTIFICATION_START";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAIL = "FETCH_NOTIFICATION_FAIL";

export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";

export const SAVE_NOTIFICATION = "SAVE_NOTIFICATION";
export const SAVE_NOTIFICATION_START = "SAVE_NOTIFICATION_START";
export const SAVE_NOTIFICATION_SUCCESS = "SAVE_NOTIFICATION_SUCCESS";
export const SAVE_NOTIFICATION_FAIL = "SAVE_NOTIFICATION_FAIL";

export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_NOTIFICATION_START = "DELETE_NOTIFICATION_START";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";

export const CONNECT_NOTIFICATION = "CONNECT_NOTIFICATION";
export const NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED";
export const CONNECT_NOTIFICATION_START = "CONNECT_NOTIFICATION_START";
export const CONNECT_NOTIFICATION_SUCCESS = "CONNECT_NOTIFICATION_SUCCESS";
export const CONNECT_NOTIFICATION_ERROR = "CONNECT_NOTIFICATION_ERROR";