export const FETCH_WEATHERS = "FETCH_WEATHERS";
export const FETCH_WEATHERS_START = "FETCH_WEATHERS_START";
export const FETCH_WEATHERS_SUCCESS = "FETCH_WEATHERS_SUCCESS";
export const FETCH_WEATHERS_FAIL = "FETCH_WEATHERS_FAIL";

export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";

export const UPDATE_WEATHER = "UPDATE_WEATHER";
export const RESET_WEATHER = "RESET_WEATHER";

export const SAVE_WEATHER = "SAVE_WEATHER";
export const SAVE_WEATHER_START = "SAVE_WEATHER_START";
export const SAVE_WEATHER_SUCCESS = "SAVE_WEATHER_SUCCESS";
export const SAVE_WEATHER_FAIL = "SAVE_WEATHER_FAIL";

export const DELETE_WEATHER = "DELETE_WEATHER";
export const DELETE_WEATHER_START = "DELETE_WEATHER_START";
export const DELETE_WEATHER_SUCCESS = "DELETE_WEATHER_SUCCESS";
export const DELETE_WEATHER_FAIL = "DELETE_WEATHER_FAIL";

export const FETCH_WEATHER_AUDIT_LOGS = "FETCH_WEATHER_AUDIT_LOGS";
export const FETCH_WEATHER_AUDIT_LOGS_START = "FETCH_WEATHER_AUDIT_LOGS_START";
export const FETCH_WEATHER_AUDIT_LOGS_SUCCESS =
  "FETCH_WEATHER_AUDIT_LOGS_SUCCESS";
export const FETCH_WEATHER_AUDIT_LOGS_FAIL = "FETCH_WEATHER_AUDIT_LOGS_FAIL";
