export const FETCH_MARGINS = "FETCH_MARGINS";
export const FETCH_MARGINS_START = "FETCH_MARGINS_START";
export const FETCH_MARGINS_SUCCESS = "FETCH_MARGINS_SUCCESS";
export const FETCH_MARGINS_FAIL = "FETCH_MARGINS_FAIL";

export const FETCH_MARGIN = "FETCH_MARGIN";
export const FETCH_MARGIN_START = "FETCH_MARGIN_START";
export const FETCH_MARGIN_SUCCESS = "FETCH_MARGIN_SUCCESS";
export const FETCH_MARGIN_FAIL = "FETCH_MARGIN_FAIL";

export const UPDATE_MARGIN = "UPDATE_MARGIN";
export const RESET_MARGIN = "RESET_MARGIN";

export const SAVE_MARGIN = "SAVE_MARGIN";
export const SAVE_MARGIN_START = "SAVE_MARGIN_START";
export const SAVE_MARGIN_SUCCESS = "SAVE_MARGIN_SUCCESS";
export const SAVE_MARGIN_FAIL = "SAVE_MARGIN_FAIL";

export const DELETE_MARGIN = "DELETE_MARGIN";
export const DELETE_MARGIN_START = "DELETE_MARGIN_START";
export const DELETE_MARGIN_SUCCESS = "DELETE_MARGIN_SUCCESS";
export const DELETE_MARGIN_FAIL = "DELETE_MARGIN_FAIL";

export const FETCH_MARGIN_AUDIT_LOGS = "FETCH_MARGIN_AUDIT_LOGS";
export const FETCH_MARGIN_AUDIT_LOGS_START = "FETCH_MARGIN_AUDIT_LOGS_START";
export const FETCH_MARGIN_AUDIT_LOGS_SUCCESS =
  "FETCH_MARGIN_AUDIT_LOGS_SUCCESS";
export const FETCH_MARGIN_AUDIT_LOGS_FAIL = "FETCH_MARGIN_AUDIT_LOGS_FAIL";
