export default {
    FETCH_NOTIFICATIONS_START: "FETCH_NOTIFICATIONS_START",
    FETCH_NOTIFICATIONS_SUCCESS: "FETCH_NOTIFICATIONS_SUCCESS",
    FETCH_NOTIFICATIONS_FAIL: "FETCH_NOTIFICATIONS_FAIL",
    CONNECT_NOTIFICATION_SUCCESS: "CONNECT_NOTIFICATION_SUCCESS",
    NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
};