export const FETCH_STOCK_NEWS = "FETCH_STOCK_NEWS";
export const FETCH_STOCK_NEWS_START = "FETCH_STOCK_NEWS_START";
export const FETCH_STOCK_NEWS_SUCCESS = "FETCH_STOCK_NEWS_SUCCESS";
export const FETCH_STOCK_NEWS_FAIL = "FETCH_STOCK_NEWS_FAIL";

export const FETCH_STOCK_NEW = "FETCH_STOCK_NEW";
export const FETCH_STOCK_NEW_START = "FETCH_STOCK_NEW_START";
export const FETCH_STOCK_NEW_SUCCESS = "FETCH_STOCK_NEW_SUCCESS";
export const FETCH_STOCK_NEW_FAIL = "FETCH_STOCK_NEW_FAIL";

export const UPDATE_STOCK_NEW = "UPDATE_STOCK_NEW";
export const RESET_STOCK_NEW = "RESET_STOCK_NEW";

export const SAVE_STOCK_NEW = "SAVE_STOCK_NEW";
export const SAVE_STOCK_NEW_START = "SAVE_STOCK_NEW_START";
export const SAVE_STOCK_NEW_SUCCESS = "SAVE_STOCK_NEW_SUCCESS";
export const SAVE_STOCK_NEW_FAIL = "SAVE_STOCK_NEW_FAIL";

export const DELETE_STOCK_NEW = "DELETE_STOCK_NEW";
export const DELETE_STOCK_NEW_START = "DELETE_STOCK_NEW_START";
export const DELETE_STOCK_NEW_SUCCESS = "DELETE_STOCK_NEW_SUCCESS";
export const DELETE_STOCK_NEW_FAIL = "DELETE_STOCK_NEW_FAIL";

//--export
