export default {
    FETCH_PAYMENTS_START: "FETCH_PAYMENTS_START",
    FETCH_PAYMENTS_SUCCESS: "FETCH_PAYMENTS_SUCCESS",
    FETCH_PAYMENTS_FAIL: "FETCH_PAYMENTS_FAIL",
    ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
    UPDATE_PAYMENT_SUCCESS: "UPDATE_PAYMENT_SUCCESS",
    DEL_PAYMENT_SUCCESS: "DEL_PAYMENT_SUCCESS",
};