export const FETCH_STOCK_GROUPS = "FETCH_STOCK_GROUPS";
export const FETCH_STOCK_GROUPS_START = "FETCH_STOCK_GROUPS_START";
export const FETCH_STOCK_GROUPS_SUCCESS = "FETCH_STOCK_GROUPS_SUCCESS";
export const FETCH_STOCK_GROUPS_FAIL = "FETCH_STOCK_GROUPS_FAIL";

export const FETCH_STOCK_GROUP = "FETCH_STOCK_GROUP";
export const FETCH_STOCK_GROUP_START = "FETCH_STOCK_GROUP_START";
export const FETCH_STOCK_GROUP_SUCCESS = "FETCH_STOCK_GROUP_SUCCESS";
export const FETCH_STOCK_GROUP_FAIL = "FETCH_STOCK_GROUP_FAIL";

export const UPDATE_STOCK_GROUP = "UPDATE_STOCK_GROUP";
export const RESET_STOCK_GROUP = "RESET_STOCK_GROUP";

export const SAVE_STOCK_GROUP = "SAVE_STOCK_GROUP";
export const SAVE_STOCK_GROUP_START = "SAVE_STOCK_GROUP_START";
export const SAVE_STOCK_GROUP_SUCCESS = "SAVE_STOCK_GROUP_SUCCESS";
export const SAVE_STOCK_GROUP_FAIL = "SAVE_STOCK_GROUP_FAIL";

export const DELETE_STOCK_GROUP = "DELETE_STOCK_GROUP";
export const DELETE_STOCK_GROUP_START = "DELETE_STOCK_GROUP_START";
export const DELETE_STOCK_GROUP_SUCCESS = "DELETE_STOCK_GROUP_SUCCESS";
export const DELETE_STOCK_GROUP_FAIL = "DELETE_STOCK_GROUP_FAIL";

export const FETCH_STOCK_GROUP_AUDIT_LOGS = "FETCH_STOCK_GROUP_AUDIT_LOGS";
export const FETCH_STOCK_GROUP_AUDIT_LOGS_START = "FETCH_STOCK_GROUP_AUDIT_LOGS_START";
export const FETCH_STOCK_GROUP_AUDIT_LOGS_SUCCESS =
  "FETCH_STOCK_GROUP_AUDIT_LOGS_SUCCESS";
export const FETCH_STOCK_GROUP_AUDIT_LOGS_FAIL = "FETCH_STOCK_GROUP_AUDIT_LOGS_FAIL";
