export const FETCH_JOB_SRCS = "FETCH_JOB_SRCS";
export const FETCH_JOB_SRCS_START = "FETCH_JOB_SRCS_START";
export const FETCH_JOB_SRCS_SUCCESS = "FETCH_JOB_SRCS_SUCCESS";
export const FETCH_JOB_SRCS_FAIL = "FETCH_JOB_SRCS_FAIL";

export const FETCH_JOB_SRC = "FETCH_JOB_SRC";
export const FETCH_JOB_SRC_START = "FETCH_JOB_SRC_START";
export const FETCH_JOB_SRC_SUCCESS = "FETCH_JOB_SRC_SUCCESS";
export const FETCH_JOB_SRC_FAIL = "FETCH_JOB_SRC_FAIL";

export const UPDATE_JOB_SRC = "UPDATE_JOB_SRC";
export const RESET_JOB_SRC = "RESET_JOB_SRC";

export const SAVE_JOB_SRC = "SAVE_JOB_SRC";
export const SAVE_JOB_SRC_START = "SAVE_JOB_SRC_START";
export const SAVE_JOB_SRC_SUCCESS = "SAVE_JOB_SRC_SUCCESS";
export const SAVE_JOB_SRC_FAIL = "SAVE_JOB_SRC_FAIL";

export const DELETE_JOB_SRC = "DELETE_JOB_SRC";
export const DELETE_JOB_SRC_START = "DELETE_JOB_SRC_START";
export const DELETE_JOB_SRC_SUCCESS = "DELETE_JOB_SRC_SUCCESS";
export const DELETE_JOB_SRC_FAIL = "DELETE_JOB_SRC_FAIL";

//--export
