export const FETCH_INDUSTRYS = "FETCH_INDUSTRYS";
export const FETCH_INDUSTRYS_START = "FETCH_INDUSTRYS_START";
export const FETCH_INDUSTRYS_SUCCESS = "FETCH_INDUSTRYS_SUCCESS";
export const FETCH_INDUSTRYS_FAIL = "FETCH_INDUSTRYS_FAIL";

export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_STOCKS_START = "FETCH_STOCKS_START";
export const FETCH_STOCKS_SUCCESS = "FETCH_STOCKS_SUCCESS";
export const FETCH_STOCKS_FAIL = "FETCH_STOCKS_FAIL";

export const FETCH_STOCK_OPTIONS = "FETCH_STOCK_OPTIONS";
export const FETCH_STOCK_OPTIONS_START = "FETCH_STOCK_OPTIONS_START";
export const FETCH_STOCK_OPTIONS_SUCCESS = "FETCH_STOCK_OPTIONS_SUCCESS";
export const FETCH_STOCK_OPTIONS_FAIL = "FETCH_STOCK_OPTIONS_FAIL";

export const FETCH_STOCK_FUNDERS = "FETCH_STOCK_FUNDERS";
export const FETCH_STOCK_FUNDERS_START = "FETCH_STOCK_FUNDERS_START";
export const FETCH_STOCK_FUNDERS_SUCCESS = "FETCH_STOCK_FUNDERS_SUCCESS";
export const FETCH_STOCK_FUNDERS_FAIL = "FETCH_STOCK_FUNDERS_FAIL";

export const FETCH_STOCK_FUNDER_SCORES = "FETCH_STOCK_FUNDER_SCORES";
export const FETCH_STOCK_FUNDER_SCORES_START = "FETCH_STOCK_FUNDER_SCORES_START";
export const FETCH_STOCK_FUNDER_SCORES_SUCCESS = "FETCH_STOCK_FUNDER_SCORES_SUCCESS";
export const FETCH_STOCK_FUNDER_SCORES_FAIL = "FETCH_STOCK_FUNDER_SCORES_FAIL";
export const TOGGLE_STOCK_TREND_LINE = "TOGGLE_STOCK_TREND_LINE";

export const FETCH_STOCK_REVENUES = "FETCH_STOCK_REVENUES";
export const FETCH_STOCK_REVENUES_START = "FETCH_STOCK_REVENUES_START";
export const FETCH_STOCK_REVENUES_SUCCESS = "FETCH_STOCK_REVENUES_SUCCESS";
export const FETCH_STOCK_REVENUES_FAIL = "FETCH_STOCK_REVENUES_FAIL";

export const FETCH_STOCK_PROFITS = "FETCH_STOCK_PROFITS";
export const FETCH_STOCK_PROFITS_START = "FETCH_STOCK_PROFITS_START";
export const FETCH_STOCK_PROFITS_SUCCESS = "FETCH_STOCK_PROFITS_SUCCESS";
export const FETCH_STOCK_PROFITS_FAIL = "FETCH_STOCK_PROFITS_FAIL";

export const FETCH_GROUP_STOCKS = "FETCH_GROUP_STOCKS";
export const FETCH_GROUP_STOCKS_SUCCESS = "FETCH_GROUP_STOCKS_SUCCESS";

export const FETCH_STOCK = "FETCH_STOCK";
export const FETCH_STOCK_EXTRA = "FETCH_STOCK_EXTRA";
export const FETCH_STOCK_START = "FETCH_STOCK_START";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
export const FETCH_STOCK_FAIL = "FETCH_STOCK_FAIL";

export const UPDATE_STOCK = "UPDATE_STOCK";
export const RESET_STOCK = "RESET_STOCK";

export const SAVE_STOCK = "SAVE_STOCK";
export const SAVE_STOCK_START = "SAVE_STOCK_START";
export const SAVE_STOCK_SUCCESS = "SAVE_STOCK_SUCCESS";
export const SAVE_STOCK_FAIL = "SAVE_STOCK_FAIL";

export const DELETE_STOCK = "DELETE_STOCK";
export const DELETE_STOCK_START = "DELETE_STOCK_START";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAIL = "DELETE_STOCK_FAIL";
export const REMOVE_LIST_STOCK = "REMOVE_LIST_STOCK";

export const FETCH_STOCK_AUDIT_LOGS = "FETCH_STOCK_AUDIT_LOGS";
export const FETCH_STOCK_AUDIT_LOGS_START = "FETCH_STOCK_AUDIT_LOGS_START";
export const FETCH_STOCK_AUDIT_LOGS_SUCCESS =
  "FETCH_STOCK_AUDIT_LOGS_SUCCESS";
export const FETCH_STOCK_AUDIT_LOGS_FAIL = "FETCH_STOCK_AUDIT_LOGS_FAIL";

//--export
export const FETCH_STOCK_FETCH_DATES = "FETCH_STOCK_FETCH_DATES";
export const FETCH_STOCK_FETCH_DATES_START = "FETCH_STOCK_FETCH_DATES_START";
export const FETCH_STOCK_FETCH_DATES_SUCCESS = "FETCH_STOCK_FETCH_DATES_SUCCESS";
export const FETCH_STOCK_FETCH_DATES_FAIL = "FETCH_STOCK_FETCH_DATES_FAIL";