export const FETCH_STOCK_DAYS = "FETCH_STOCK_DAYS";
export const FETCH_STOCKS_DAYS = "FETCH_STOCKS_DAYS";
export const FETCH_STOCK_DAYS_START = "FETCH_STOCK_DAYS_START";
export const FETCH_STOCK_DAYS_SUCCESS = "FETCH_STOCK_DAYS_SUCCESS";
export const FETCH_STOCKS_DAYS_SUCCESS = "FETCH_STOCKS_DAYS_SUCCESS";
export const FETCH_STOCK_DAYS_FAIL = "FETCH_STOCK_DAYS_FAIL";

export const FETCH_STOCK_DAY = "FETCH_STOCK_DAY";
export const FETCH_STOCK_DAY_START = "FETCH_STOCK_DAY_START";
export const FETCH_STOCK_DAY_SUCCESS = "FETCH_STOCK_DAY_SUCCESS";
export const FETCH_STOCK_DAY_FAIL = "FETCH_STOCK_DAY_FAIL";

export const RESET_STOCK_DAY = "RESET_STOCK_DAY";

