export const FETCH_MATCHS = "FETCH_MATCHS";
export const FETCH_MATCHS_START = "FETCH_MATCHS_START";
export const FETCH_MATCHS_SUCCESS = "FETCH_MATCHS_SUCCESS";
export const FETCH_MATCHS_FAIL = "FETCH_MATCHS_FAIL";

export const FETCH_MATCH = "FETCH_MATCH";
export const FETCH_MATCH_START = "FETCH_MATCH_START";
export const FETCH_MATCH_SUCCESS = "FETCH_MATCH_SUCCESS";
export const FETCH_MATCH_FAIL = "FETCH_MATCH_FAIL";

export const UPDATE_MATCH = "UPDATE_MATCH";
export const RESET_MATCH = "RESET_MATCH";

export const SAVE_MATCH = "SAVE_MATCH";
export const SAVE_MATCH_START = "SAVE_MATCH_START";
export const SAVE_MATCH_SUCCESS = "SAVE_MATCH_SUCCESS";
export const SAVE_MATCH_FAIL = "SAVE_MATCH_FAIL";

export const DELETE_MATCH = "DELETE_MATCH";
export const DELETE_MATCH_START = "DELETE_MATCH_START";
export const DELETE_MATCH_SUCCESS = "DELETE_MATCH_SUCCESS";
export const DELETE_MATCH_FAIL = "DELETE_MATCH_FAIL";

export const FETCH_MATCH_AUDIT_LOGS = "FETCH_MATCH_AUDIT_LOGS";
export const FETCH_MATCH_AUDIT_LOGS_START = "FETCH_MATCH_AUDIT_LOGS_START";
export const FETCH_MATCH_AUDIT_LOGS_SUCCESS =
  "FETCH_MATCH_AUDIT_LOGS_SUCCESS";
export const FETCH_MATCH_AUDIT_LOGS_FAIL = "FETCH_MATCH_AUDIT_LOGS_FAIL";
