export default {
    FETCH_WORDS: "FETCH_WORDS",
    FETCH_WORD: "FETCH_WORD",
    FETCH_WORD_STATS_PAGED: "FETCH_WORD_STATS_PAGED",
    ADD_WORD: "ADD_WORD",
    UPDATE_WORD: "UPDATE_WORD",
    UPDATE_WORDS: "UPDATE_WORDS",
    DEL_WORD: "DEL_WORD",
};