export default {
    FETCH_WORDS_START: "FETCH_WORDS_START",
    FETCH_WORDS_SUCCESS: "FETCH_WORDS_SUCCESS",
    FETCH_WORD_STATS_PAGED_SUCCESS: "FETCH_WORD_STATS_PAGED_SUCCESS",
    FETCH_WORDS_FAIL: "FETCH_WORDS_FAIL",
    ADD_WORD_SUCCESS: "ADD_WORD_SUCCESS",
    UPDATE_WORD_SUCCESS: "UPDATE_WORD_SUCCESS",
    UPDATE_WORDS_SUCCESS: "UPDATE_WORDS_SUCCESS",
    DEL_WORD_SUCCESS: "DEL_WORD_SUCCESS",
};