export const FETCH_SEMINARS = "FETCH_SEMINARS";
export const FETCH_SEMINARS_START = "FETCH_SEMINARS_START";
export const FETCH_SEMINARS_SUCCESS = "FETCH_SEMINARS_SUCCESS";
export const FETCH_SEMINARS_FAIL = "FETCH_SEMINARS_FAIL";

export const FETCH_SEMINAR = "FETCH_SEMINAR";
export const FETCH_SEMINAR_START = "FETCH_SEMINAR_START";
export const FETCH_SEMINAR_SUCCESS = "FETCH_SEMINAR_SUCCESS";
export const FETCH_SEMINAR_FAIL = "FETCH_SEMINAR_FAIL";

export const UPDATE_SEMINAR = "UPDATE_SEMINAR";
export const RESET_SEMINAR = "RESET_SEMINAR";

export const SAVE_SEMINAR = "SAVE_SEMINAR";
export const SAVE_SEMINAR_START = "SAVE_SEMINAR_START";
export const SAVE_SEMINAR_SUCCESS = "SAVE_SEMINAR_SUCCESS";
export const SAVE_SEMINAR_FAIL = "SAVE_SEMINAR_FAIL";

export const DELETE_SEMINAR = "DELETE_SEMINAR";
export const DELETE_SEMINAR_START = "DELETE_SEMINAR_START";
export const DELETE_SEMINAR_SUCCESS = "DELETE_SEMINAR_SUCCESS";
export const DELETE_SEMINAR_FAIL = "DELETE_SEMINAR_FAIL";
