export const FETCH_CALENDARS = "FETCH_CALENDARS";
export const FETCH_CALENDARS_START = "FETCH_CALENDARS_START";
export const FETCH_CALENDARS_SUCCESS = "FETCH_CALENDARS_SUCCESS";
export const FETCH_CALENDARS_FAIL = "FETCH_CALENDARS_FAIL";

export const FETCH_CALENDAR = "FETCH_CALENDAR";
export const FETCH_CALENDAR_START = "FETCH_CALENDAR_START";
export const FETCH_CALENDAR_SUCCESS = "FETCH_CALENDAR_SUCCESS";
export const FETCH_CALENDAR_FAIL = "FETCH_CALENDAR_FAIL";

export const UPDATE_CALENDAR = "UPDATE_CALENDAR";
export const RESET_CALENDAR = "RESET_CALENDAR";

export const SAVE_CALENDAR = "SAVE_CALENDAR";
export const SAVE_CALENDAR_START = "SAVE_CALENDAR_START";
export const SAVE_CALENDAR_SUCCESS = "SAVE_CALENDAR_SUCCESS";
export const SAVE_CALENDAR_FAIL = "SAVE_CALENDAR_FAIL";

export const DELETE_CALENDAR = "DELETE_CALENDAR";
export const DELETE_CALENDAR_START = "DELETE_CALENDAR_START";
export const DELETE_CALENDAR_SUCCESS = "DELETE_CALENDAR_SUCCESS";
export const DELETE_CALENDAR_FAIL = "DELETE_CALENDAR_FAIL";
