export default {
    FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
    FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_FAIL: "FETCH_QUESTIONS_FAIL",
    ADD_QUESTION_SUCCESS: "ADD_QUESTION_SUCCESS",
    UPDATE_QUESTION_SUCCESS: "UPDATE_QUESTION_SUCCESS",
    DEL_QUESTION_SUCCESS: "DEL_QUESTION_SUCCESS",
};