export const FETCH_STOCK_NOTES = "FETCH_STOCK_NOTES";
export const FETCH_ALL_STOCK_NOTES = "FETCH_ALL_STOCK_NOTES";
export const FETCH_STOCK_NOTES_START = "FETCH_STOCK_NOTES_START";
export const FETCH_STOCK_NOTES_SUCCESS = "FETCH_STOCK_NOTES_SUCCESS";
export const FETCH_STOCK_NOTE_Paged_SUCCESS = "FETCH_STOCK_NOTE_Paged_SUCCESS";
export const FETCH_STOCK_NOTES_FAIL = "FETCH_STOCK_NOTES_FAIL";

export const FETCH_STOCK_NOTE = "FETCH_STOCK_NOTE";
export const FETCH_STOCK_NOTE_START = "FETCH_STOCK_NOTE_START";
export const FETCH_STOCK_NOTE_SUCCESS = "FETCH_STOCK_NOTE_SUCCESS";
export const FETCH_STOCK_NOTE_FAIL = "FETCH_STOCK_NOTE_FAIL";

export const UPDATE_STOCK_NOTE = "UPDATE_STOCK_NOTE";
export const RESET_STOCK_NOTE = "RESET_STOCK_NOTE";

export const SAVE_STOCK_NOTE = "SAVE_STOCK_NOTE";
export const SAVE_STOCK_NOTE_START = "SAVE_STOCK_NOTE_START";
export const SAVE_STOCK_NOTE_SUCCESS = "SAVE_STOCK_NOTE_SUCCESS";
export const SAVE_STOCK_NOTE_FAIL = "SAVE_STOCK_NOTE_FAIL";

export const DELETE_STOCK_NOTE = "DELETE_STOCK_NOTE";
export const DELETE_STOCK_NOTE_START = "DELETE_STOCK_NOTE_START";
export const DELETE_STOCK_NOTE_SUCCESS = "DELETE_STOCK_NOTE_SUCCESS";
export const DELETE_STOCK_NOTE_FAIL = "DELETE_STOCK_NOTE_FAIL";

export const FETCH_STOCK_NOTE_AUDIT_LOGS = "FETCH_STOCK_NOTE_AUDIT_LOGS";
export const FETCH_STOCK_NOTE_AUDIT_LOGS_START = "FETCH_STOCK_NOTE_AUDIT_LOGS_START";
export const FETCH_STOCK_NOTE_AUDIT_LOGS_SUCCESS =
  "FETCH_STOCK_NOTE_AUDIT_LOGS_SUCCESS";
export const FETCH_STOCK_NOTE_AUDIT_LOGS_FAIL = "FETCH_STOCK_NOTE_AUDIT_LOGS_FAIL";
