export const FETCH_WEATHERS = "FETCH_WEATHERS";
export const FETCH_WEATHERS_START = "FETCH_WEATHERS_START";
export const FETCH_WEATHERS_SUCCESS = "FETCH_WEATHERS_SUCCESS";
export const FETCH_WEATHERS_FAIL = "FETCH_WEATHERS_FAIL";

export const FETCH_WEATHER_ALARM = "FETCH_WEATHER_ALARM";
export const FETCH_WEATHER_TIDAL = "FETCH_WEATHER_TIDAL";
export const FETCH_WEATHER_RECENT = "FETCH_WEATHER_RECENT";
export const FETCH_WEATHER_EARTHQUAKE = "FETCH_WEATHER_EARTHQUAKE";
export const FETCH_WEATHER_COUNTY = "FETCH_WEATHER_COUNTY";
export const FETCH_WEATHER_OBSERVATION = "FETCH_WEATHER_OBSERVATION";

export const FETCH_WEATHER_ALARM_SUCCESS = "FETCH_WEATHER_ALARM_SUCCESS";
export const FETCH_WEATHER_TIDAL_SUCCESS = "FETCH_WEATHER_TIDAL_SUCCESS";
export const FETCH_WEATHER_RECENT_SUCCESS = "FETCH_WEATHER_RECENT_SUCCESS";
export const FETCH_WEATHER_EARTHQUAKE_SUCCESS = "FETCH_WEATHER_EARTHQUAKE_SUCCESS";
export const FETCH_WEATHER_COUNTY_SUCCESS = "FETCH_WEATHER_COUNTY_SUCCESS";
export const FETCH_WEATHER_OBSERVATION_SUCCESS = "FETCH_WEATHER_OBSERVATION_SUCCESS";

export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";

export const RESET_WEATHER = "RESET_WEATHER";