export default {
    FETCH_PROFILES_START: "FETCH_PROFILES_START",
    FETCH_PROFILES_SUCCESS: "FETCH_PROFILES_SUCCESS",
    FETCH_PROFILES_FAIL: "FETCH_PROFILES_FAIL",
    ADD_PROFILE_SUCCESS: "ADD_PROFILE_SUCCESS",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    DEL_PROFILE_SUCCESS: "DEL_PROFILE_SUCCESS",
};