export const FETCH_REVENUES = "FETCH_REVENUES";
export const FETCH_REVENUES_START = "FETCH_REVENUES_START";
export const FETCH_REVENUES_SUCCESS = "FETCH_REVENUES_SUCCESS";
export const FETCH_REVENUES_FAIL = "FETCH_REVENUES_FAIL";

export const FETCH_REVENUE = "FETCH_REVENUE";
export const FETCH_REVENUE_START = "FETCH_REVENUE_START";
export const FETCH_REVENUE_SUCCESS = "FETCH_REVENUE_SUCCESS";
export const FETCH_REVENUE_FAIL = "FETCH_REVENUE_FAIL";

export const UPDATE_REVENUE = "UPDATE_REVENUE";
export const RESET_REVENUE = "RESET_REVENUE";

export const SAVE_REVENUE = "SAVE_REVENUE";
export const SAVE_REVENUE_START = "SAVE_REVENUE_START";
export const SAVE_REVENUE_SUCCESS = "SAVE_REVENUE_SUCCESS";
export const SAVE_REVENUE_FAIL = "SAVE_REVENUE_FAIL";

export const DELETE_REVENUE = "DELETE_REVENUE";
export const DELETE_REVENUE_START = "DELETE_REVENUE_START";
export const DELETE_REVENUE_SUCCESS = "DELETE_REVENUE_SUCCESS";
export const DELETE_REVENUE_FAIL = "DELETE_REVENUE_FAIL";
