export default {
    FETCH_CALENDAR: "FETCH_CALENDAR",
    FETCH_CALENDARS: "FETCH_CALENDARS",
    ADD_CALENDAR: "ADD_CALENDAR",
    UPDATE_CALENDAR: "UPDATE_CALENDAR",
    DEL_CALENDAR: "DEL_CALENDARS",
    FETCH_CALENDARCATEGORIES: "FETCH_CALENDARCATEGORIES",
};