export default {
    FETCH_CALENDARS_START: "FETCH_CALENDARS_START",
    FETCH_CALENDAR_SUCCESS: "FETCH_CALENDAR_SUCCESS",
    FETCH_CALENDARS_SUCCESS: "FETCH_CALENDARS_SUCCESS",
    FETCH_CALENDARS_FAIL: "FETCH_CALENDARS_FAIL",
    ADD_CALENDAR_SUCCESS: "ADD_CALENDAR_SUCCESS",
    UPDATE_CALENDAR_SUCCESS: "UPDATE_CALENDAR_SUCCESS",
    DEL_CALENDAR_SUCCESS: "DEL_CALENDAR_SUCCESS",
    FETCH_CALENDAR_CATEGORYS_SUCCESS: "FETCH_CALENDAR_CATEGORYS_SUCCESS",
};