export default {
    FETCH_CALENDARS_START: "FETCH_CALENDARS_START",
    FETCH_CALENDARS_SUCCESS: "FETCH_CALENDARS_SUCCESS",
    FETCH_CALENDARS_FAIL: "FETCH_CALENDARS_FAIL",
    ADD_CALENDARS_SUCCESS: "ADD_CALENDARS_SUCCESS",
};