export const FETCH_FUNDERS = "FETCH_FUNDERS";
export const FETCH_FUNDERS_START = "FETCH_FUNDERS_START";
export const FETCH_FUNDERS_SUCCESS = "FETCH_FUNDERS_SUCCESS";
export const FETCH_FUNDERS_FAIL = "FETCH_FUNDERS_FAIL";

export const FETCH_FUNDER = "FETCH_FUNDER";
export const FETCH_FUNDER_START = "FETCH_FUNDER_START";
export const FETCH_FUNDER_SUCCESS = "FETCH_FUNDER_SUCCESS";
export const FETCH_FUNDER_FAIL = "FETCH_FUNDER_FAIL";

export const UPDATE_FUNDER = "UPDATE_FUNDER";
export const RESET_FUNDER = "RESET_FUNDER";

export const SAVE_FUNDER = "SAVE_FUNDER";
export const SAVE_FUNDER_START = "SAVE_FUNDER_START";
export const SAVE_FUNDER_SUCCESS = "SAVE_FUNDER_SUCCESS";
export const SAVE_FUNDER_FAIL = "SAVE_FUNDER_FAIL";

export const DELETE_FUNDER = "DELETE_FUNDER";
export const DELETE_FUNDER_START = "DELETE_FUNDER_START";
export const DELETE_FUNDER_SUCCESS = "DELETE_FUNDER_SUCCESS";
export const DELETE_FUNDER_FAIL = "DELETE_FUNDER_FAIL";

//--export
export const FETCH_FUNDER_SCORES = "FETCH_FUNDER_SCORES";
export const FETCH_FUNDER_SCORES_START = "FETCH_FUNDER_SCORES_START";
export const FETCH_FUNDER_SCORES_SUCCESS = "FETCH_FUNDER_SCORES_SUCCESS";
export const FETCH_FUNDER_SCORES_FAIL = "FETCH_FUNDER_SCORES_FAIL";