export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_LOCATION_START = "FETCH_LOCATION_START";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";

export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const RESET_LOCATION = "RESET_LOCATION";

export const SAVE_LOCATION = "SAVE_LOCATION";
export const SAVE_LOCATION_START = "SAVE_LOCATION_START";
export const SAVE_LOCATION_SUCCESS = "SAVE_LOCATION_SUCCESS";
export const SAVE_LOCATION_FAIL = "SAVE_LOCATION_FAIL";

export const DELETE_LOCATION = "DELETE_LOCATION";
export const DELETE_LOCATION_START = "DELETE_LOCATION_START";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";

export const FETCH_LOCATION_AUDIT_LOGS = "FETCH_LOCATION_AUDIT_LOGS";
export const FETCH_LOCATION_AUDIT_LOGS_START = "FETCH_LOCATION_AUDIT_LOGS_START";
export const FETCH_LOCATION_AUDIT_LOGS_SUCCESS =
  "FETCH_LOCATION_AUDIT_LOGS_SUCCESS";
export const FETCH_LOCATION_AUDIT_LOGS_FAIL = "FETCH_LOCATION_AUDIT_LOGS_FAIL";
