export const FETCH_PROFITS = "FETCH_PROFITS";
export const FETCH_PROFITS_START = "FETCH_PROFITS_START";
export const FETCH_PROFITS_SUCCESS = "FETCH_PROFITS_SUCCESS";
export const FETCH_PROFITS_FAIL = "FETCH_PROFITS_FAIL";

export const FETCH_PROFIT = "FETCH_PROFIT";
export const FETCH_PROFIT_START = "FETCH_PROFIT_START";
export const FETCH_PROFIT_SUCCESS = "FETCH_PROFIT_SUCCESS";
export const FETCH_PROFIT_FAIL = "FETCH_PROFIT_FAIL";

export const UPDATE_PROFIT = "UPDATE_PROFIT";
export const RESET_PROFIT = "RESET_PROFIT";

export const SAVE_PROFIT = "SAVE_PROFIT";
export const SAVE_PROFIT_START = "SAVE_PROFIT_START";
export const SAVE_PROFIT_SUCCESS = "SAVE_PROFIT_SUCCESS";
export const SAVE_PROFIT_FAIL = "SAVE_PROFIT_FAIL";

export const DELETE_PROFIT = "DELETE_PROFIT";
export const DELETE_PROFIT_START = "DELETE_PROFIT_START";
export const DELETE_PROFIT_SUCCESS = "DELETE_PROFIT_SUCCESS";
export const DELETE_PROFIT_FAIL = "DELETE_PROFIT_FAIL";